<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class StatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // $table->string('step')->comment('ขั้นตอน');
        // $table->string('name')->comment('คำอธิบาย');
        // $table->foreignId('role_id')->comment('ประเภทบุคลากร');
        DB::table('master_statuses')->insert([

            // Step 1 การเสนอหัวข้อ
            [
                'role_id' => '1',
                'step' => '1',
                'name' => 'เสนอหัวข้อ',
                'status' => 'รออนุมัติ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '1',
                'name' => 'เสนอหัวข้อ',
                'status' => 'อนุมัติหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '1',
                'name' => 'เสนอหัวข้อ',
                'status' => 'ไม่อนุมัติหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '1',
                'name' => 'เสนอหัวข้อ',
                'status' => 'อนุมัติหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '1',
                'name' => 'เสนอหัวข้อ',
                'status' => 'ไม่อนุมัติหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],

             // Step 2 การสอบหัวข้อ
             [
                'role_id' => '1',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'รออนุมัติขอสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'อนุมัติขอสอบหัวข้อ ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'ไม่อนุมัติขอสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'อนุมัติขอสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'ไม่อนุมัติขอสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],

            [
                'role_id' => '2',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'ผ่านการสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'ผ่านแบบมีเงื่อนไขการสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'ไม่ผ่านการสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '2',
                'name' => 'สอบหัวข้อ',
                'status' => 'อนุมัติผลการสอบหัวข้อ',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],



            // Step 3 การก้าวหน้า
            [
                'role_id' => '1',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'รออนุมัติขอสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'อนุมัติขอสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'ไม่อนุมัติขอสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'อนุมัติขอสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'ไม่อนุมัติขอสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],

            [
                'role_id' => '2',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'ผ่านการสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'ผ่านแบบมีเงื่อนไขการสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'ไม่ผ่านการสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '3',
                'name' => 'ก้าวหน้า',
                'status' => 'อนุมัติผลการสอบก้าวหน้า',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],


             // Step 4 การสอบป้องกัน
             [
                'role_id' => '1',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'รออนุมัติขอสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'อนุมัติขอสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'ไม่อนุมัติขอสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'อนุมัติขอสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'ไม่อนุมัติขอสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],

            [
                'role_id' => '2',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'ผ่านการสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'ผ่านแบบมีเงื่อนไขการสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'ไม่ผ่านการสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '4',
                'name' => 'ป้องกัน',
                'status' => 'อนุมัติผลการสอบป้องกัน',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],


               // Step 5 การสอบป้องกัน
            [
                'role_id' => '1',
                'step' => '5',
                'name' => 'ส่งเลม',
                'status' => 'รออนุมัติการส่งเลม',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],

            [
                'role_id' => '2',
                'step' => '5',
                'name' => 'ส่งเลม',
                'status' => 'ผ่านการส่งเลม',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '5',
                'name' => 'ส่งเลม',
                'status' => 'ผ่านแบบมีเงื่อนไขการส่งเลม',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '2',
                'step' => '5',
                'name' => 'ส่งเลม',
                'status' => 'ไม่ผ่านการส่งเลม',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
            [
                'role_id' => '3',
                'step' => '5',
                'name' => 'ส่งเลม',
                'status' => 'อนุมัติผลการส่งเลม',
                'created_by' => 1,
                'created_at' => now(),
                'updated_by' => 1,
                'updated_at' => now(),
            ],
        ]);
    }
}
